"""create tickets

Revision ID: 303f512199c9
Revises: 1bd06de28a2b
Create Date: 2026-07-24 12:32:55.655508

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "303f512199c9"
down_revision: str | Sequence[str] | None = "1bd06de28a2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="ticketvisibilitytype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW_QUESTION",
                "ASSIGNED",
                "IN_PROGRESS",
                "RESOLVED",
                "CLOSED",
                name="ticketstatustype",
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("support_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["support_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickets_created_by_user_id"), "tickets", ["created_by_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_support_user_id"), "tickets", ["support_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQLではFK制約が張られたままインデックスを個別にdropできないため、
    # テーブルごとdropして外部キー・インデックスもまとめて削除する
    op.drop_table("tickets")
    # ### end Alembic commands ###
